### ISSUE TITLE
Install fail on Synology NAS Docker

### ISSUE THREAD

**Issue by SxS46** [Jawesome99/IW4x#14]
The install fails when doing this:
# This hack is necessary, because it is the only way to install 32-bit wine on 64-bit alpine.
RUN echo "x86" > /etc/apk/arch &&\
        apk add --no-cache wine &&\
        echo "x86_64" > /etc/apk/arch &&\
        addgroup -g ${GROUP_ID} iw4x &&\
        adduser -h "/iw4x" -G iw4x -D -u ${USER_ID} iw4x
With this error:
BusyBox v1.28.4 (2018-12-31 18:05:15 UTC) multi-call binary.

Usage: addgroup [-g GID] [-S] [USER] GROUP

Add a group or add a user to a group

        -g GID  Group id
        -S      Create a system group
Removing intermediate container 7f016d4488fc
ERROR: Service 'server' failed to build: The command '/bin/sh -c echo "x86" > /etc/apk/arch &&        apk add --no-cache wine &&        echo "x86_64" > /etc/apk/arch &&        addgroup -g ${GROUP_ID} iw4x &&        adduser -h "/iw4x" -G iw4x -D -u ${USER_ID} iw4x' returned a non-zero code: 1
Any ideas?
Thank you

**Comment by Emosewaj** [comment]
Unrelated to repository.
