### ISSUE TITLE
Current system fails to properly analyze keywords due to non-alphanumeric symbols

### ISSUE THREAD

**Issue by Emosewaj** [Jawesome99/IW4x#2]
The current system can't analyze keywords properly if the text contains special characters such as questionmarks, dots, commas, etc. Filtering those out might be a good start to get an idea of how regex works. I'm sure regex can be implemented into that.

**Comment by Hexman768** [comment]
I'm a junior software developer and I'd love to help you out here, first thing though...there are conflicting tags on this issue. Is this issue a bug or is it an enhancement? Basically, was this functionality intended to work originally and just doesn't [bug]? Or is this a new feature that you would like to implement [enhancement]?

**Comment by Emosewaj** [comment]
Closing, bot files have been moved as of [279158e](https://github.com/Emosewaj/IW4x/commit/279158e61f5f32cc33c3ae021e35120706b48c6f), new repository for bot is Emosewaj/[x-labs-bot](https://github.com/Emosewaj/x-labs-bot) (private).
