### ISSUE TITLE
Missing InitGame Details in games_mp.log

### ISSUE THREAD

**Issue by GrizwoldCoD** [Jawesome99/IW4x#8]
Hi,

in games_mp.log the InitGame entry is without details (mapname, gametype,..) as shown in log below. Therefore b3 and xlrstats are not showing proper map and retrieveng calculating correct stats.

> - 0:00 ------------------------------------------------------------
> -   0:00 InitGame
> -   0:50 ShutdownGame:
> -   0:50 ------------------------------------------------------------
> -   0:50 ------------------------------------------------------------
> -   0:50 InitGame
> -   7:07 ShutdownGame:
> -   7:07 ------------------------------------------------------------
> -   7:07 ------------------------------------------------------------
> -   7:07 InitGame
> -   8:12 J;eac0b6df2485dae6;0;GrizwoldCoD
> -   8:24 K;eac0b6df2485dae6;0;allies;GrizwoldCoD;eac0b6df2485dae6;0;allies;GrizwoldCoD;frag_grenade_mp;128;MOD_GRENADE_SPLASH;none
> -   9:04 K;eac0b6df2485dae6;0;allies;GrizwoldCoD;eac0b6df2485dae6;0;allies;GrizwoldCoD;frag_grenade_mp;132;MOD_GRENADE_SPLASH;none
> -   9:54 D;eac0b6df2485dae6;0;allies;GrizwoldCoD;;-1;world;;none;74;MOD_FALLING;none
> -  10:43 Q;eac0b6df2485dae6;0;GrizwoldCoD
> -  11:57 J;eac0b6df2485dae6;0;GrizwoldCoD
> -  12:08 say;eac0b6df2485dae6;0;GrizwoldCoD;!map
> -  12:17 say;eac0b6df2485dae6;0;GrizwoldCoD;!map_rotation
> -  12:34 say;eac0b6df2485dae6;0;GrizwoldCoD;!maps
> -  12:49 say;eac0b6df2485dae6;0;GrizwoldCoD;!maprotate
> -  12:50 ShutdownGame:
> -  12:50 ------------------------------------------------------------
> -  12:50 ------------------------------------------------------------
> -  12:50 InitGame
> -  13:00 J;eac0b6df2485dae6;0;GrizwoldCoD
> -  15:45 Q;eac0b6df2485dae6;0;GrizwoldCoD
> -   0:00 ------------------------------------------------------------
> -   0:00 InitGame
> -   0:22 ShutdownGame:
> -   0:22 ------------------------------------------------------------
> -   0:22 ------------------------------------------------------------
> -   0:22 InitGame

I believe it should be something like that (Taken from CoD4 OW)

> 0:00 InitGame: \fs_game\mods/openwarfare_beta\g_compassShowEnemies\0\g_gametype\war\gamename\Call of Duty 4\mapname\mp_crash\protocol\6\shortversion\1.7\sv_allowAnonymous\0\sv_disableClientConsole\0\sv_floodprotect\1\sv_hostname\^7CoD4:MW ^3OpenWarfare\sv_maxclients\32\sv_maxPing\0\sv_maxRate\25000\sv_minPing\0\sv_privateClients\0\sv_punkbuster\0\sv_pure\1\sv_voice\1\ui_maxclients\32
 
Also this is b3 parser for CoD (https://github.com/BigBrotherBot/big-brother-bot/blob/master/b3/parsers/cod.py):

```
def OnInitgame(self, action, data, match=None):
options = re.findall(r'\\([^\\]+)\\([^\\]+)', data)
        for o in options:
            if o[0] == 'mapname':
                self.game.mapName = o[1]
            elif o[0] == 'g_gametype':
                self.game.gameType = o[1]
            elif o[0] == 'fs_game':
                self.game.modName = o[1]
            else:
                setattr(self.game, o[0], o[1])
        self.verbose('...self.console.game.gameType: %s' % self.game.gameType)
        self.game.startRound()
        return self.getEvent('EVT_GAME_ROUND_START', data=self.game)
```

**Comment by Jawesome99** [comment]
Unrelated to the content hosted on this repository. If you want to submit this to the devs, find someone on the Discord.

/closed
